apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: health-dashboard
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: goal-app
  destination:
    namespace: goal-app
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/tuolden/health-dashboard.git'
    targetRevision: main
    path: kubernetes
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=false
      - Replace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
