apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: health-dashboard
  namespace: goal-app
  labels:
    app: health-dashboard
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  tls:
  - hosts:
    - dashboard.home
    secretName: health-dashboard-tls
  rules:
  - host: dashboard.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: health-dashboard
            port:
              number: 80
