apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Health Dashboard Complete Deployment
# Deploy with: kubectl apply -k kubernetes/

namespace: goal-app

resources:
  # Frontend
  - deployment.yaml
  - service.yaml
  - ingress.yaml

  # Backend
  - ../server/kubernetes/deployment.yaml
  - ../server/kubernetes/service.yaml
  - ../server/kubernetes/ingress.yaml

# Common labels for all resources
commonLabels:
  app.kubernetes.io/name: health-dashboard
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/component: web-app

# Force image updates on deployment
images:
  - name: black:32003/health-dashboard
    newTag: latest
  - name: black:32003/health-dashboard-api
    newTag: latest
